### ISSUE TITLE
Drawer doesn't actually create links

### ISSUE THREAD

**Issue by georgiosd** [OrigenStudio/material-ui-layout#57]
Hi!

It seems that the drawer(s) don't actually create links, just list items.

In fact, `href` is completely ignored.

Georgios

**Comment by PolGuixe** [comment]
@georgiosd thanks for reporting it. I'll investigate it.

**Comment by PolGuixe** [comment]
@georgiosd It should be fixed in the v.0.1.0-rc5. 
Let me know if you have any problems.
